languageCode = 'en-us'
title = 'Ryan Kavanagh'
author = 'Ryan Kavanagh' 
email = 'contact@ryanguitar.uk'
baseURL = 'https://ryanguitar.uk/'
theme = 'nostyleplease' 

#This allows inline html in markdown 
ignoreLogs = ['warning-goldmark-raw-html']
[markup.goldmark.renderer]
    unsafe = true

#nostyleplease requires this for the favicon to appear correctly
[params]
    favicon = "/favicon.ico"


[taxonomies]
#Leaving this empty prevents /tags and /categories being generated